In [1]:
import tkinter

In [1]:
fin = lambda x, y:x+y

In [2]:
fin(1,2)

3

In [3]:
a = [0,1,2,3]

In [5]:
a[len(a):] = [4]

In [6]:
a

[0, 1, 2, 3, 4]

In [8]:
class DOG:
    kind = 'canine'
    def __init__(self, name):
        self.name = name

In [10]:
DOG('hello')

### 类中的方法声明有3种，常规方法def、类方法@classmethod、静态方法@staticmethod

In [11]:
class A:
    __privateVar = 0 #私有变量
    publicVar = 0    #公有变量
    def __init__(self, value=0):
        self.mvalue = value
    @classmethod     #类方法
    def class_foo(cls, x):
        cls.__privateVar += x
        print ('cls：',cls.__privateVar)
    @staticmethod   #静态方法
    def static_foo(x):
        A.publicVar += x
        print ('static：',A.publicVar)

### 类属性@property

In [13]:
import math
class Circle:
    def __init__(self, radius):
        self.radius = radius
    @property    #类属性
    def area(self):
        return math.pi*self.radius**2
C = Circle(10)
C.area

314.1592653589793

### 类继承

In [20]:
class person:
    def __init__(self, name, age, sex):
        self.name = name
        self.age = age
        self.sex = sex
    def showinfo(self):
        print ('persion：',self.name, self.age, self.sex)
class teacher(person):
    def __init__(self, name, age, sex, course, department):
        person.__init__(self, name, age, sex)
        self.course = course
        self.department = department
    def showinfo(cls):
        print ('teacher：',cls.name, cls.age, cls.sex, cls.course, cls.department)
a = person('Zhou', 20, '男')
b = teacher('Zhou', 20, '男', '数学', '李园')
a.showinfo()
b.showinfo()

persion： Zhou 20 男
teacher： Zhou 20 男 数学 李园


In [1]:
import numpy as np
z = np.array([[1,2,3,4],[5,6,7,8]])

In [2]:
print(z)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
z.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a = z.reshape(-1)

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
z is a

False

In [8]:
a is z

False

In [1]:
%time print('hello')

hello
Wall time: 0 ns


In [3]:
%time import tensorflow

Wall time: 0 ns


### list

In [2]:
a = [1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
a.index(1)  # 索引

0

In [5]:
a.append(10) # 尾插

In [6]:
a

[1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
a.clear() # 清空

In [8]:
a

[]

In [10]:
b = a.copy() # 复制
b.append(5)

In [13]:
a, b

([], [5])

In [15]:
b = [1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b.count(1) # 计算某元素出现次数

3

In [17]:
b.extend([10,11]) # 合并列表
b

[1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [19]:
b.insert(0, 0) # 插入
b

[0, 1, 1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [23]:
b.pop(1)  # 弹出（参数为索引）
b

[0, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [24]:
b.remove(1) # 移除（参数为值）
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [25]:
b.reverse() # 倒置
b

[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [28]:
b.sort(key=lambda x:x, reverse=False) # 排序
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

### tuple

In [29]:
a = (1,2,3,4)
a[:2]

(1, 2)

### str

In [30]:
st = "zhougang"

In [32]:
s1 = st.capitalize() # 首字母大写，其他小写
s1

'Zhougang'

In [34]:
s2 = st.casefold()
s2

'zhougang'

In [37]:
s3 = st.center(11, '0')
st, s3

('zhougang', '00zhougang0')

### map

In [4]:
a = [1, 2, 3, 4]
b = list(map(lambda x:x**2, a))
print(b)

[1, 4, 9, 16]


In [5]:
def multiply(x):
    return x*x
def add(x):
    return x+x
funcs = [multiply, add]
for i in range(5):
    value = list(map(lambda x:x(i), funcs))
    print(value)

[0, 0]
[1, 2]
[4, 4]
[9, 6]
[16, 8]


### Filter

In [6]:
number_list = range(-5, 5)
list(filter(lambda x: x<0, number_list))

[-5, -4, -3, -2, -1]

### 装饰器

In [2]:
def a_new_decorator(a_func):
    def wrapTheFunction():
        print('hello')
        a_func()
        print('hello')
    return wrapTheFunction

@a_new_decorator
def a_function_requiring_decoration():
    """Hey you! Decorate me"""
    print('function')

a_function_requiring_decoration()
print(a_function_requiring_decoration.__name__) #名字被改写

hello
function
hello
wrapTheFunction


In [3]:
from functools import wraps

def a_new_decorator(a_func):
    @wraps(a_func)
    def wrapTheFunction():
        print('hello')
        a_func()
        print('hello')
    return wrapTheFunction

@a_new_decorator
def a_function_requiring_decoration():
    "hey"
    print('decorator')

a_function_requiring_decoration()
print(a_function_requiring_decoration.__name__)

hello
decorator
hello
a_function_requiring_decoration


### 函数标注

In [2]:
def person() ->str:
    return "hello"

### 文档字符串

In [3]:
def my_function():
    """Do nothing, but ducument it.
    """
    pass
print(my_function.__doc__)

Do nothing, but ducument it.
    


### 推导式

In [5]:
[(x, y) for x in [1,2,3] for y in [2,1,4] if x!=y]

[(1, 2), (1, 4), (2, 1), (2, 4), (3, 2), (3, 1), (3, 4)]

In [6]:
[(x, y) for x in [1,2,3,4,5,6] if x%2==0 for y in [1,2,3,4,5,6] if y%2==1]

[(2, 1), (2, 3), (2, 5), (4, 1), (4, 3), (4, 5), (6, 1), (6, 3), (6, 5)]

### 格式化

In [7]:
import math
print(f"The value of pi is:{math.pi:.3f}")

The value of pi is:3.142


In [9]:
for i in range(1,11):
    print(repr(i).rjust(2), repr(i*i).rjust(3), repr(i**3).rjust(4))

 1   1    1
 2   4    8
 3   9   27
 4  16   64
 5  25  125
 6  36  216
 7  49  343
 8  64  512
 9  81  729
10 100 1000


### 文件

In [5]:
f = open("../Text.txt",mode="r")
for l in f:
    print(l, end='')
f.close()

This is the first line of the file.
Second line of the file.

In [14]:
f = open("Text.txt",mode="r")
l = f.readline()
while l:
    print(l,end='')
    l = f.readline()
f.close()

This is the first line of the file.
Second line of the file.

In [12]:
with open("test.txt", mode="w") as f:
    f.write("hello,this is a write test")

In [13]:
f.closed

True

### json

### 异常

In [20]:
try:
    a = 5/0
except ZeroDivisionError as inst:
    print(inst)
else:
    print(a)

division by zero


In [21]:
try:
    raise Exception("error1", "error2", "error3") # 手动抛出
except Exception as e:
    print(e)

('error1', 'error2', 'error3')


In [22]:
class Error(Exception):
    """This is a Error."""
    pass
class myError(Error):
    def __init__(self, message):
        self.message = message
raise myError("myError")

myError: myError

### 迭代器

In [2]:
class Reverse:
    def __init__ (self, data):
        self.data = data
        self.index = len(data)
    def __iter__ (self):
        return self
    def __next__(self):
        if self.index == 0:
            raise StopIteration
        self.index -= 1
        return self.data[self.index]
rev = Reverse("spam")
r = iter(rev)
print(next(r))
print(next(r))
print(next(r))
print(next(r))
print(next(r))

m
a
p
s


StopIteration: 

In [4]:
for char in rev:
    print(char)

m
a
p
s


### 生成器

In [1]:
sum(i*i for i in range(10))

285

In [2]:
xvec = [10, 20, 30]
yvec = [7, 5, 3]
sum(x*y for x,y in zip(xvec, yvec))

260

In [4]:
set(x for x in [1, 2, 5])

{1, 2, 5}

### 标准库简介

In [ ]:
from urllib.request import urlopen
with urlopen('http://tycho.usno.navy.mil/cgi-bin/timer.pl') as response:
    for line in response:
        line = line.decode('utf-8')
        if 'EST' in line or 'EDT' in line:
            print(line)

In [6]:
from datetime import date
now = date.today()
now

datetime.date(2019, 12, 30)

In [7]:
from timeit import Timer
Timer('t=a;a=b;b=t', 'a=1;b=2').timeit()

0.027629799999886018

In [8]:
Timer('a, b = b, a', 'a=1;b=2').timeit()

0.024055500000031316

In [10]:
from array import array
a = array('H', [4000, 10, 700, 22222])
sum(a)

26932

In [11]:
a[1:3]

array('H', [10, 700])

In [ ]:
import 